# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
